/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KASU;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
import javax.swing.ButtonGroup;
import javafx.event.ActionEvent;
//import java.awt.event.ActionListener; 
//import java.awt.event.KeyAdapter;
//import java.awt.event.KeyEvent;
import java.awt.event.*; 
import java.util.ArrayList;
import java.util.List;
import java.awt.*; 
/**
 *
 * @author Himms
 */
public class Questions extends javax.swing.JFrame {
    
     
                  
                    
   

    /**
     * Creates new form Questions
     */
    

   //  double stop_timer = 0;
   
     int score = 0;
     private List<JRadioButton> correctButtons;
     // ButtonGroup bg1 = new ButtonGroup();
     
    public int questionCount = 1;
 
    
   
    public Questions() {
        initComponents();
      //  groupButton();
           
        
    }
    
    /**
     *
     * @return
     */
        
   
    
    public JTextArea getjTextArea1(){
    return this.jTextArea1;
    }
   
    public void setjTextArea1(javax.swing.JTextArea jTextArea1 ){
       this.jTextArea1 = jTextArea1;
   }
    
     public JTextField getjTextField1(){
    return this.jTextField1;
    }
   
    public void setjTextField1(javax.swing.JTextField jTextField1 ){
       this.jTextField1 = jTextField1;
   }
    public JTextField getjTextField2(){
    return this.jTextField2;
    }
   
    public void setjTextField2(javax.swing.JTextField jTextField2 ){
       this.jTextField2 = jTextField2;
   }
    
    public JTextField getregText(){
    return this.regText;
    }
   
    public void setjregText(javax.swing.JTextField regText ){
       this.regText = regText;
   }
    
     public JRadioButton getBtn1(){
    return this.jRadioButton1;
    }
   
    public void setBtn1(javax.swing.JRadioButton jRadioButton1 ){
       this.jRadioButton1 = jRadioButton1;
   }
    
     public JRadioButton getBtn2(){
    return this.jRadioButton2;
    }
   
    public void setBtn2(javax.swing.JRadioButton jRadioButton2){
       this.jRadioButton2 = jRadioButton2;
   }
    
    public JRadioButton getBtn3(){
    return this.jRadioButton3;
    }
   
    public void setBtn3(javax.swing.JRadioButton jRadioButton3 ){
       this.jRadioButton3 = jRadioButton3;
   }
    
     public JRadioButton getBtn4(){
    return this.jRadioButton4;
    }
   
    public void setBtn4(javax.swing.JRadioButton jRadioButton4 ){
       this.jRadioButton4 = jRadioButton4;
   }
    
    
//    public void groupButton()  {
//   
//        
//    
//      bg1.add(jRadioButton1);
//     
//      bg1.add(jRadioButton2);
//     
//      bg1.add(jRadioButton3);
//    
//      bg1.add(jRadioButton4);
//     
//    }
    
    public void clearRadioButtons(){
     
    buttonGroup1.clearSelection();
    }
     
     
  
    /**
     *
     * @param model
    * @param selected
    */
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        regText = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Time left: 07:21");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Next");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Question No.");

        regText.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Course Code");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton1)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jButton3))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(regText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(14, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton3)))
                .addGap(36, 36, 36)
                .addComponent(jRadioButton1)
                .addGap(26, 26, 26)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

//   public void getAnswer(){ 
//   
//   }
        try {
            System.out.println("demo2");

            Class.forName("com.mysql.jdbc.Driver"); //mysql database connection
            String database = "jdbc:mysql://localhost:3306/studentdb";
            System.out.println("Yayi");
            Connection con = DriverManager.getConnection(database, "root", "");
            System.out.println("Demo3");

            Statement sql = con.createStatement();
            System.out.println("demo4");

            String query = "SELECT * from questions order by qid ASC limit " + this.questionCount + ",1";
            System.out.println("okay sql: " + query);
            ResultSet rs = sql.executeQuery(query);
            System.out.println("Demo6");
           
            if (rs.next()) {
                //rs.setText(String(valueOfNext(rs.next());

                    System.out.println("Demo7");
                    int qid = rs.getInt("qid");
                    String course = rs.getString("course");
                    String question = rs.getString("question");
                    String option_a = rs.getString("option_a");
                    String option_b = rs.getString("option_b");
                    String option_c = rs.getString("option_c");
                    String option_d = rs.getString("option_d");

                    String ans = rs.getString("ans");
                    System.out.println(ans);
                   
                    String btext = Integer.toString(qid);
                  
                    jTextField1.setText(btext);
                    jTextField2.setText(course);
                    jTextArea1.setText(question);
                    
                  
                    jRadioButton1.setText(option_a);
                   
                    jRadioButton2.setText(option_b);
                    
                    jRadioButton3.setText(option_c);
                   
                    jRadioButton4.setText(option_d); 
                  
                    
                    
                    System.out.println("Demo8");
                    
                    
                    
                    if (jRadioButton1.isSelected() && ans.equalsIgnoreCase(option_a)){
                                           //break;
                                            score += 1;
                                            
                                             }
                                 
                
                    else if (jRadioButton2.isSelected() && ans.equalsIgnoreCase(option_b)){
                                            score += 1;
                                            
                                       }
                                  
                
                    else  if (jRadioButton3.isSelected() && ans.equalsIgnoreCase(option_c)){
                                        score += 1;
                                       }
                                  
                    else  if  (jRadioButton4.isSelected() && ans.equalsIgnoreCase(option_d)){
                                        score += 1;
                                       }
                    
                        else{ score += 0;} 

//
//                    

   rs.close();
                    
                    
                    
/** Another way of adding scores is by creating an array of the answered questions as follows:
   by importing util Arraylist and list and also creating arrays:
 private List<JRadioButton> correctButtons; and correctButtons = new ArrayList<JRadioButton>();
*/

//                                      correctButtons = new ArrayList<JRadioButton>();
//
//                                       if (ans.equalsIgnoreCase(option_a)){
//                                           correctButtons.add(jRadioButton1);
//                    
//                                      }
//                                       else if (ans.equalsIgnoreCase(option_b)){
//                                      correctButtons.add(jRadioButton2);
//                                      }
//                                       else if (ans.equalsIgnoreCase(option_c)){
//                                       correctButtons.add(jRadioButton3);
//                                       }
//                                       else if (ans.equalsIgnoreCase(option_d)){
//                                       correctButtons.add(jRadioButton4);
//                                       }
//                                       System.out.println("!@@");
//
//                                       for (JRadioButton correctButton : correctButtons){
//
//                                      if(correctButton.isSelected()){
//                                                 score++;
//
//                                             }
//                                               System.out.println(score);
//                                              }
//
//
               clearRadioButtons();
//                   
           }
            
        
                      
            else  {

                JOptionPane.showMessageDialog( null, "You're done. Click submit to end exams" );
                
            }
        
        }
   
        catch (ClassNotFoundException | SQLException | HeadlessException e)

        {
            JOptionPane.showMessageDialog(null, "NOT CALLED");
        }
   
        this.questionCount++;
        
        
   

        try {

            Class.forName("com.mysql.jdbc.Driver"); //mysql database connection
            String database = "jdbc:mysql://localhost:3306/studentdb";
            Connection con = DriverManager.getConnection(database, "root", "");
            System.out.println("Demo8");

            Statement sql = con.createStatement();
            System.out.println("demo9");
            StudentLogin sl = new StudentLogin ();
           
            String query = "update std_login set score = '"+score+"' where reg_no = '"+regText.getText()+"'";  

            System.out.println("okay sql: " + query);

            System.out.println("Demo10");

            sql.executeUpdate(query);

        }
        catch (Exception e){

        }
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JOptionPane.showMessageDialog(null,"Hello " + regText.getText() + " you scored = " + score, "STUDENT RESULT", JOptionPane.INFORMATION_MESSAGE);
        
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
   
  
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

         
                      
              
          

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
                
                
//                
            }
        });
                                  
                    
            
    }
    
    
            
//   private void r1MouseClicked(java.awt.event.MouseEvent evt) {                                     
//        
//     getBtn1();
//    }                                    
//    private void r2MouseClicked(java.awt.event.MouseEvent evt) {                                     
//            getBtn2();   
//    }                                    
//
//    private void r3MouseClicked(java.awt.event.MouseEvent evt) {                                     
//        getBtn3();
//    }  
//    
//     private void r4MouseClicked(java.awt.event.MouseEvent evt) {                                     
//        getBtn4();
//    }             
         

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField regText;
    // End of variables declaration//GEN-END:variables

   

   

    
    
    
}
